<?php echo $header?>
<div class="container-fluid">
	<div class="row" id="infogarantia">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<p>Bienvenidos al mundo de TUMI, la marca l&iacute;der internacional de accesorios para viajes, negocios y estilo de vida. Desde 1975, TUMI se ha dedicado a ofrecerles a nuestros clientes una excepcional experiencia como propietarios. La cobertura integral de productos de TUMI refleja nuestro compromiso con la satisfacci&oacute;n continua de nuestros consumidores. Espec&iacute;ficamente, asumimos tres compromisos con nuestros clientes:</p>
			<ol>
				<li>Disfrutar&aacute; al utilizar nuestros productos innovadores que est&aacute;n dise&ntilde;ados y fabricados para ser los mejores;</li> 
				<li>Experimentar&aacute; un servicio de atenci&oacute;n al cliente de posventa de primera categor&iacute;a;</li>
				<li>Durante cinco (5) a&ntilde;os despu&eacute;s de adquirir un producto de TUMI de una de nuestras colecciones de viajes, negocios y maletas, o dos (2) a&ntilde;os para cualquier billetera o accesorio, en una tienda o distribuidor autorizado de Tumi, tendr&aacute; la cobertura de nuestra garant&iacute;a limitada.</li>
			</ol>
			<p>La garant&iacute;a de TUMI se otorga al propietario original, es sencilla e integral, y es solamente una parte de la experiencia total de ser propietario de un producto de TUMI.</p>
			
			<h2 class="bold">Primer a&ntilde;o de propiedad: sin preocupaciones</h2> 
			<p>Con excepciones limitadas, si su producto de TUMI se deteriora durante los primeros doce (12) meses de propiedad&mdash;incluido el deterioro provocado por uso y desgaste, l&iacute;neas a&eacute;reas u otro tipo de deterioro causado durante los viajes&mdash;TUMI cubrir&aacute; todos los gastos de reparaciones, incluso los costos de env&iacute;o a y desde nuestro centro de reparaciones. Si determinamos que el producto no tiene posibilidades de reparaci&oacute;n, lo reemplazaremos. Si determinamos que no disponemos de un producto de reemplazo, le daremos un producto de un valor comparable. El deterioro que no est&aacute; cubierto es el provocado por abuso, deterioro cosm&eacute;tico (como cuero rayado o tela manchada) y el deterioro incidental o emergente, como deterioro o p&eacute;rdida del contenido de una bolsa, p&eacute;rdida de uso, p&eacute;rdida de tiempo o gastos similares.</p> 
			
			<h2 class="bold">Del segundo al quinto a&ntilde;o para maletas, maletines de negocios, bandoleras, bolsos, mochilas y carteras, y desde el segundo a&ntilde;o en el que sea propietario de billeteras, accesorios y prendas de abrigo: tiene cobertura por defectos de fabricaci&oacute;n y provocados por el uso y desgaste. </h2> 
			<p>Desde el comienzo del segundo a&ntilde;o y hasta el final del quinto a&ntilde;o en los que sea propietario de un art&iacute;culo de viaje, malet&iacute;n de negocios u otra maleta de TUMI, y desde el segundo a&ntilde;o en el que sea propietario de billeteras, accesorios o prendas de abrigo, TUMI reparar&aacute; los art&iacute;culos con defectos provocados por el uso y desgaste, defectos en los materiales o de mano de obra, incluidos defectos estructurales (como asas, cremalleras o cierres defectuosos). Por el segundo hasta el quinto a&ntilde;o, no cubriremos el deterioro provocado por l&iacute;neas a&eacute;reas ni ning&uacute;n otro producido durante los viajes. Los reclamos por deterioro producido durante los viajes deben presentarse a la compa&ntilde;&iacute;a a&eacute;rea. Tampoco est&aacute; cubierto el deterioro provocado por abuso, deterioro cosm&eacute;tico (como cuero rayado o tela manchada) y el deterioro incidental o emergente, como deterioro o p&eacute;rdida del contenido de una bolsa, p&eacute;rdida de uso, p&eacute;rdida de tiempo o gastos similares. El uso o desgaste normal de las prendas de abrigo de TUMI no incluye p&eacute;rdida de botones, telas o pieles desgarradas o deterioro cosm&eacute;tico como se describe anteriormente. </p> 
			
			<p>Su &uacute;nica responsabilidad es enviarnos su art&iacute;culo para que lo reparemos, con el franqueo prepagado, o traerlo a una tienda TUMI o distribuidor de TUMI autorizado, quien con mucho gusto procesar&aacute; la reparaci&oacute;n. En algunos casos puede aplicarse una tarifa nominal de procesamiento. De hecho, muchas reparaciones pueden realizarse en la tienda TUMI, sin costo. Si su art&iacute;culo debe enviarse a nuestro centro, lo repararemos r&aacute;pidamente y lo enviaremos de regreso sin costo adicional para usted. En los casos poco comunes en los que nuestra garant&iacute;a no se aplique, su centro de servicios local le ofrecer&aacute; un presupuesto de cualquier costo de reparaci&oacute;n y env&iacute;o de regreso en que se pueda incurrir.</p>
			
			<h2 class="bold">Puede esperar a&ntilde;os de un servicio de calidad</h2>
			<p>Tenemos muchos clientes con bolsas de m&aacute;s de cinco a&ntilde;os y muchos a&ntilde;os de viaje a quienes les gustar&iacute;a renovar o reparar sus bolsas. A estos clientes les ofrecemos un servicio cort&eacute;s y diligente, adem&aacute;s de la m&aacute;s alta calidad en reparaciones y renovaciones a un costo razonable. Si no podemos reparar la bolsa, sugeriremos opciones alternativas. Llame a nuestro centro de servicio local antes de enviar su producto para reparaci&oacute;n o renovaci&oacute;n y hablaremos sobre los costos de manipulaci&oacute;n y env&iacute;o, y otras tarifas. </p> 
			
			<h2 class="bold">Compromiso total</h2> 
			<p>Lo esencial es que, en TUMI, tenemos un compromiso total de mantenerlo satisfecho con nuestros productos y servicios. Una vez que haya tenido el placer de poseer y utilizar nuestros productos, esperamos que se conviertan en sus fieles acompa&ntilde;antes de por vida. Puede comunicarse con nosotros las 24 horas del d&iacute;a, los siete d&iacute;as de la semana, en <a href="/my-account/repair-services">TUMI.com/my-account/repair-services</a>. Si vive en los Estados Unidos o Canad&aacute;, llame al 800.781.TUMI (8864) de 8:00 a. m. a 4:45 p. m. para hablar con un representante del servicio de atenci&oacute;n al cliente. Para comunicarse con el servicio de atenci&oacute;n al cliente de TUMI fuera de los Estados Unidos y Canad&aacute;, consulte la lista de centros internacionales en la secci&oacute;n &quot;Service and Repair&quot; (Servicios y reparaciones) en esta p&aacute;gina web. </p> 
			
			<h2 class="bold">Comprobante de compra</h2> 
			<p>Guarde su recibo de la tienda como comprobante de compra. Lo necesitar&aacute; para demostrar su cobertura de garant&iacute;a. Adem&aacute;s, le servir&aacute; como comprobante de que realiz&oacute; su compra en un punto de venta autorizado por TUMI. Nuestra garant&iacute;a limitada se aplica &uacute;nicamente a productos comprados en una tienda o un distribuidor autorizado de TUMI.</p> 
			
			<p>Visite el siguiente enlace y perm&iacute;tanos gestionar su comprobante de compra por usted. <a href="/tumi-tracer/register-your-tumi ">TUMI.com/tumi-tracer/register-your-tumi</a></p> 
			
			
			<p>Al inscribirse en el programa TUMI Tracer&reg;, la fecha de compra queda registrada de modo que su informaci&oacute;n estar&aacute; en nuestro sistema. En caso de que necesite utilizar nuestros servicios de reparaci&oacute;n, podemos verificar si su maleta a&uacute;n est&aacute; dentro de la garant&iacute;a. No todos los art&iacute;culos que hacemos tienen un n&uacute;mero de seguimiento, pero la mayor&iacute;a de nuestro equipaje, maletas y maletines de negocios lo tienen. Si el art&iacute;culo en cuesti&oacute;n no est&aacute; registrado en TUMI Tracer&reg;, ser&aacute; su responsabilidad proporcionar un comprobante de compra de un punto de venta autorizado por TUMI. </p> 
			
			<p>Esta garant&iacute;a le concede determinados derechos y es posible que tambi&eacute;n tenga otros derechos, que pueden variar de un estado a otro o entre los distintos pa&iacute;ses de Europa. Algunas jurisdicciones no permiten la exclusi&oacute;n o la limitaci&oacute;n de da&ntilde;os indirectos o incidentales; por ello, es posible que la limitaci&oacute;n o la exclusi&oacute;n anteriores no correspondan a su caso.</p> 
		</div>
	</div>
</div>